PCB: false
batchsize: 32
color_jitter: false
data_dir: ./pytorch_re_id
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
lr: 0.05
name: ft_ResNet50
nclasses: 82
stride: 2
train_all: false
use_NAS: false
use_dense: false
warm_epoch: 0
